export const COMMON_BIOMARKERS = [
  {
    name: "Colesterol Total",
    name_normalized: "total_cholesterol",
    unit: "mg/dL",
    ref_min: 0,
    ref_max: 200,
  },
  {
    name: "Colesterol LDL",
    name_normalized: "ldl",
    unit: "mg/dL",
    ref_min: 0,
    ref_max: 130,
  },
  {
    name: "Colesterol HDL",
    name_normalized: "hdl",
    unit: "mg/dL",
    ref_min: 40,
    ref_max: 60,
  },
  {
    name: "Triglicéridos",
    name_normalized: "triglycerides",
    unit: "mg/dL",
    ref_min: 0,
    ref_max: 150,
  },
  {
    name: "Glicose",
    name_normalized: "glucose",
    unit: "mg/dL",
    ref_min: 70,
    ref_max: 100,
  },
  {
    name: "HbA1c",
    name_normalized: "hba1c",
    unit: "%",
    ref_min: 4.0,
    ref_max: 5.7,
  },
  {
    name: "Hemoglobina",
    name_normalized: "hemoglobin",
    unit: "g/dL",
    ref_min: 13.0,
    ref_max: 17.5,
  },
  {
    name: "Creatinina",
    name_normalized: "creatinine",
    unit: "mg/dL",
    ref_min: 0.7,
    ref_max: 1.3,
  },
  {
    name: "TFG estimada",
    name_normalized: "egfr",
    unit: "mL/min",
    ref_min: 90,
    ref_max: 120,
  },
  {
    name: "TSH",
    name_normalized: "tsh",
    unit: "mUI/L",
    ref_min: 0.4,
    ref_max: 4.0,
  },
  {
    name: "Proteína C Reactiva",
    name_normalized: "crp",
    unit: "mg/L",
    ref_min: 0,
    ref_max: 3.0,
  },
  {
    name: "Ácido Úrico",
    name_normalized: "uric_acid",
    unit: "mg/dL",
    ref_min: 3.5,
    ref_max: 7.0,
  },
  {
    name: "Ferro sérico",
    name_normalized: "iron",
    unit: "µg/dL",
    ref_min: 60,
    ref_max: 170,
  },
  {
    name: "Ferritina",
    name_normalized: "ferritin",
    unit: "ng/mL",
    ref_min: 20,
    ref_max: 250,
  },
  {
    name: "Vitamina D",
    name_normalized: "vitamin_d",
    unit: "ng/mL",
    ref_min: 30,
    ref_max: 100,
  },
] as const;
